/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_pinguo_camera360_Hello */

#ifndef _Included_com_pinguo_camera360_Hello
#define _Included_com_pinguo_camera360_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pinguo_camera360_Hello
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pinguo_camera360_Hello_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_pinguo_camera360_Hello
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pinguo_camera360_Hello_getStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
