/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_pinguo_camera360_Hello */
#include "com_pinguo_camera360_Hello.h"
JNIEXPORT jstring JNICALL Java_com_pinguo_camera360_Hello_getStringFromNative(JNIEnv *env,jclass jclazz){
  return "getStringFromNative";
}

JNIEXPORT jstring JNICALL
Java_com_pinguo_camera360_Hello_getStringFromJNI(JNIEnv *env, jclass type) {
    return "getStringFromJNI";
}